pub mod buffer;
pub mod channel_layout;
pub mod chroma_location;
pub mod codec_id;
pub mod color_primaries;
pub mod color_trc;
pub mod error;
pub mod frame;
pub mod frame_side_data;
pub mod log;
pub mod media_type;
pub mod metadata;
pub mod packet;
pub mod pixel_format;
pub mod rational;
pub mod sample_format;
pub mod timestamp;

// Re-export key types at the crate root for convenience.
pub use buffer::Buffer;
pub use channel_layout::ChannelLayout;
pub use chroma_location::ChromaLocation;
pub use codec_id::CodecId;
pub use color_primaries::ColorPrimaries;
pub use color_trc::ColorTransferCharacteristic;
pub use error::{Error, Result};
pub use frame::Frame;
pub use frame_side_data::{FrameSideData, FrameSideDataType};
pub use media_type::MediaType;
pub use metadata::Metadata;
pub use packet::Packet;
pub use pixel_format::PixelFormat;
pub use rational::Rational;
pub use sample_format::SampleFormat;
pub use timestamp::{NOPTS_VALUE, TIME_BASE, TIME_BASE_Q};
