// Build script for wedeo-codec-h264: compiles FFmpeg NEON assembly via `cc`.
//
// When the `asm` feature is enabled and the target is aarch64, this script:
// 1. Generates a `config.h` and `config_components.h` in OUT_DIR
// 2. Compiles the vendored .S files into a static library
// 3. Emits `cargo:rustc-cfg=has_asm` so Rust code can detect it

fn main() {
    // Declare the custom cfg so rustc's check-cfg doesn't warn.
    println!("cargo::rustc-check-cfg=cfg(has_asm)");

    #[cfg(feature = "asm")]
    build_asm();
}

#[cfg(feature = "asm")]
fn build_asm() {
    let arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    let os = std::env::var("CARGO_CFG_TARGET_OS").unwrap();

    if arch == "aarch64" {
        build_aarch64(&os);
    }
    // Future: "arm", "x86_64", "x86" — silent fallback to pure Rust
}

#[cfg(feature = "asm")]
fn build_aarch64(os: &str) {
    let out_dir = std::env::var("OUT_DIR").unwrap();

    generate_config_h(&out_dir, os);
    generate_config_components_h(&out_dir);

    let asm_dir = "asm/aarch64";

    // Tell cargo to re-run if assembly files change.
    println!("cargo:rerun-if-changed={asm_dir}");

    cc::Build::new()
        .flag("-x")
        .flag("assembler-with-cpp")
        // Include OUT_DIR first (for config.h, config_components.h)
        .include(&out_dir)
        // Include the asm directory (for asm.S, neon.S cross-includes)
        .include(asm_dir)
        .file(format!("{asm_dir}/h264qpel_neon.S"))
        .file(format!("{asm_dir}/h264idct_neon.S"))
        .file(format!("{asm_dir}/h264dsp_neon.S"))
        .file(format!("{asm_dir}/h264cmc_neon.S"))
        // h264pred_neon.S is not wired up yet, but compile it for future use
        .file(format!("{asm_dir}/h264pred_neon.S"))
        .compile("wedeo_h264_asm");

    println!("cargo:rustc-cfg=has_asm");
}

/// Generate `config.h` with platform-specific defines that `asm.S` needs.
#[cfg(feature = "asm")]
fn generate_config_h(out_dir: &str, os: &str) {
    // macOS uses underscore prefix for external symbols; Linux/ELF does not.
    let (extern_prefix, extern_asm) = match os {
        "macos" | "ios" | "tvos" | "watchos" | "visionos" => ("\"_\"", "_"),
        _ => ("\"\"", ""),
    };

    // macOS doesn't support .func directive; Linux does.
    let have_as_func: u8 = if os == "linux" { 1 } else { 0 };

    // ELF targets support .section .data.rel.ro
    let have_section_data_rel_ro: u8 = if os == "linux" { 1 } else { 0 };

    let config = format!(
        r#"/* Generated by wedeo build.rs — do not edit */
#ifndef WEDEO_CONFIG_H
#define WEDEO_CONFIG_H

#define EXTERN_PREFIX {extern_prefix}
#define EXTERN_ASM {extern_asm}

#define HAVE_AS_FUNC {have_as_func}

/* Architecture directives — Apple clang and GNU as both support these on aarch64 */
#define HAVE_AS_ARCH_DIRECTIVE 1
#define AS_ARCH_LEVEL armv8-a

/* Extension directives — safe to enable, only used to gate .arch_extension */
#define HAVE_AS_ARCHEXT_CRC_DIRECTIVE 1
#define HAVE_AS_ARCHEXT_DOTPROD_DIRECTIVE 1
#define HAVE_AS_ARCHEXT_I8MM_DIRECTIVE 1
#define HAVE_AS_ARCHEXT_SVE_DIRECTIVE 1
#define HAVE_AS_ARCHEXT_SVE2_DIRECTIVE 1
#define HAVE_AS_ARCHEXT_SME_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SME_I16I64_DIRECTIVE 0
#define HAVE_AS_ARCHEXT_SME2_DIRECTIVE 0

#define HAVE_SECTION_DATA_REL_RO {have_section_data_rel_ro}
#define HAVE_SME 0

#endif /* WEDEO_CONFIG_H */
"#
    );

    std::fs::write(format!("{out_dir}/config.h"), config).expect("Failed to write config.h");
}

/// Generate `config_components.h` — disables non-H.264 codecs that share
/// some assembly files (e.g. h264cmc_neon.S has RV40/VC1 blocks).
#[cfg(feature = "asm")]
fn generate_config_components_h(out_dir: &str) {
    let config = r#"/* Generated by wedeo build.rs — do not edit */
#ifndef WEDEO_CONFIG_COMPONENTS_H
#define WEDEO_CONFIG_COMPONENTS_H

/* Only H.264 — disable RV40/VC1 blocks in shared assembly files */
#define CONFIG_RV40_DECODER 0
#define CONFIG_VC1DSP 0

#endif /* WEDEO_CONFIG_COMPONENTS_H */
"#;

    std::fs::write(format!("{out_dir}/config_components.h"), config)
        .expect("Failed to write config_components.h");
}
